apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-web-app.fullname" . }}-frontend-nginx-config
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  default.conf: |-
    server {
      listen {{ .Values.frontend.service.port }};
      server_name _;

      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }

