apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "my-web-app.fullname" . }}-frontend
  labels:
    {{- include "my-web-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "my-web-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "my-web-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.service.port }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          livenessProbe:
{{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
{{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "my-web-app.fullname" . }}-frontend-nginx-config
            items:
              - key: default.conf
                path: default.conf

